### ISSUE TITLE
Numbered list number partially hidden

### ISSUE THREAD

**Issue by ricardobayes** [HubRise/website#102]
![livepepper_numbered](https://user-images.githubusercontent.com/6675237/82887768-5f129c80-9f40-11ea-8281-e92cd8a69947.JPG)

In https://www.hubrise.com/apps/livepepper/getting-started/ number 10 is not visible.
If I set 'overflow: none' for the < ol >, it shows up correctly.

**Comment by antmonnier** [comment]
Tx for pointing out, will fix in the next release.
