### ISSUE TITLE
Files to download from the Drive

### ISSUE THREAD

**Issue by janainawittner** [HubRise/website#144]
@antmonnier; what you have done in the QuickStart Guide to download a zip file is not great.
https://www.hubrise.com/fr/developers/quick-start

Here is what someone not connected to Google sees: https://take.ms/nFlL4

Giving access to a folder in the Drive works much better as you can see the files, even if you are not connected to Google. 

If you prefer to create this folder in your Drive and not in mine, please do it and share the link with me as I need to upload the logos to share in our branding page too.

**Comment by antmonnier** [comment]
Moved files to a personal folder.
