### ISSUE TITLE
[Uber Eats] New FAQ: "Can orders be sent directly to my EPOS without validation on the Uber Eats tablet?"

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#159]
Here is an email exchange with Louis (Uber Eats) to help you craft an answer:

**Janaina:** 
The owner [of the restaurant] tells me that he does not need to accept the order on the tablet before details are sent to HubRise which is great. 
I thought orders would need to be accepted on the tablet first. Could you please confirm that this same workflow will work for all restaurants we are connecting?

**Louis:**
We actually handle both modes from our end: Manual (injection is done when order is validated on the tablet) or direct (injection is done directly).

Would like all your stores to be by default setup on direct injection? I can update our config routine as such.
If you have partners preferring manual, you can always specify it to our Tech support team when requesting the config.

**Janaina:**
Thank you for the prompt response. 
Can the restaurant owner decide himself to go from a manual to a direct injection?
Ideally, they would start manual for a few weeks to make sure everything works as expected and then set it to direct. 
If there is some way to integrate this, we can develop a switch in our HubRise Uber Eats Bridge back office.

**Louis:**
The restaurant can indeed decide on their own, together with their Eats Account Manager. The setup is currently not exposed through API, unfortunately.
I'll let you know if this changes.

**Comment by atorin** [comment]
Sorry for commit 54643f3, I was using the wrong branch.
