### ISSUE TITLE
[Deliveroo] Finding the location ID & activating the connection

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#172]
- Is the setup procedure identical to Uber Eats (= HubRise sends an email to Deliveroo support team), or can it be done by the customer on its own?

- If HubRise sends an email, this should be documented in a support wiki, in the same fashion as https://github.com/HubRise/support/wiki/Uber-Eats

**Comment by antmonnier** [comment]
cc @janainawittner

**Comment by atorin** [comment]
@antmonnier @janainawittner I have created a specific page for Deliveroo in the `support` repo. Onboarding is a bit different from Uber, but still HubRise's responsibility.

**Comment by atorin** [comment]
I've also updated the onboarding process in the docs.
See #174
