### ISSUE TITLE
[Uber Eats & Deliveroo] Add terminology page

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#173]
In the same fashion as LIvePepper http://localhost:8000/apps/livepepper/livepepper-terms/

**Comment by atorin** [comment]
OK good idea! I'll add these pages.

I'm not sure about the current title: "LivePepper Terms"... It makes me think of "Terms and Conditions". Can we find another word? Like "terminology", "vocabulary", "jargon", "glossary"... 

cc @janainawittner

**Comment by janainawittner** [comment]
Good point Alberto. 
Initially, this page was called App1 terms vs App2 terms but we tried to shorten it for the whole title to hold in a single line.
Why not just call ist **Terminology**, **Key Terminology**, **Terminology Mix**. Definitely no need to have the App's name there. It does not att anything.

CC: @antmonnier

**Comment by atorin** [comment]
@janainawittner I have opted for a very simple "Key Words", but feel free to pick a different choice.

Regarding the actual terms, you will see that some are missing from the tables. Let me know if you have any ideas on if/how to fill them. Thanks!

**Comment by janainawittner** [comment]
@atorin, I replied directly in the Pull Request. It's easier....
I could not help much. I have not yet started on Deliveroo, so I don't have much to say. 
However, in the Uber Eats page, I think we should include Store UUID.
