### ISSUE TITLE
[Uber Eats] configuration into

### ISSUE THREAD

**Issue by janainawittner** [HubRise/website#178]
Some feedback on: 
https://www.hubrise.com/apps/uber-eats/configuration/

The screenshot shows payment type : online. 
I think third_party needs to be selected, no?
It can be misleading if third_party should always be selected.

Should we not write in bold the UI references we are speaking about? And explain each of these points a little better.

- The **Service type ref code** associated to Uber Eats orders [in your EPOS? Without such reference your EPOS will not know that this order comes from Uber Eats?]
- The **Payment type** [I would include a specific line for this and explain the available options are for. I still don't understand it myself]
- The **Payment ref code** associated with Uber Eats orders [in your EPOS? Without it bla bla bla]
- The **Disposable items ref code** used when a customer includes disposable items in an order. [why not explain here what it is but make a separate paragraph below? Just wondering....]

----- Also ----- 

This is a supper important sentence which should probably be included before the bullet points above. 
"Special ref codes associated with Uber Eats might be required by your EPOS for service type and payment. Refer to your connected EPOS documentation on the HubRise website to verify."

----- And finally ----- 

**Disposable items** is an option that clients can tick in the Uber Eats basket on checkout. 

- Can we have a screenshot of a Uber Eats basket with this option to show clearly what it is?

Not all restaurants include this option in their basket but if they do, they need to include the ref code.

- Can we explain how to include a ref code? An item needs to be created in the EPOS and the corresponding ref code will be included here. If this is not the case for ALL EPOS, we can say something along the lines of, for most EPOS solutions.... refer to your EPOS documentation on the HubRise website to verify.

**Comment by antmonnier** [comment]
(I'm leaving this to @atorin )

**Comment by atorin** [comment]
Hi @janainawittner! 
You'll find my changes here: https://github.com/HubRise/website/pull/174/commits/3a23badcaaa0ab8ce60b1ba7fe2839442e5fc19f

1 - Regarding the screenshot of the Configuration page
>I think third_party needs to be selected, no?

I took that from a live store (I don't remember which one) and they use `online`. So I think both options can be used by restaurants. I have included this info in the text. 

2 - Regarding the screenshot of the Uber Eats restaurant, I'm not sure if we want to highlight the "Disposable items" checkbox with a red box or something. Let me know and I will update the screenshot.

3 - Regarding the "Disposable items" paragraph. I've kept it as a single block, but I'm not sure if we want to split it into two separate parts (one in the bullet, one after). Let me know what you think.

**Comment by janainawittner** [comment]
@alberto, 

Even though I loaded your branch, for some reason I cannot see this page on: http://localhost:8000/apps/uber-eats/
Never mind....

Here is my feedback:

1. **online** should always been selected. Antoine just explained that he has created the **third_party** for an EPOS called Nestor but he might remove it. So, we should select **online** always. 

2. I prefer without the red box. No need to update. 
However, I would remove this sentence from the bullet point and include it in it's own paragraph, above the image: 
*The following screenshot shows the **Request utensils, straws, etc.** checkbox that customers can use to request disposable items.*

I cannot see this in context but I think it will be better....

3. I would simplify this bullet point a bit more
Actual sentence: *But if they do, they need to provide this ref code in the configuration. You also need to create the corresponding product in the EPOS, with matching ref code. Refer to your connected EPOS documentation on the HubRise website for the exact procedure.*

To be replaced by something along the lines of: *If you do, you need to provide a ref code. Create a "Disposable items" product in your EPOS, and use this ref code here.*

I don't think we will document how to create a product in the EPOS section, so, no need to refer to it here I think.

**Comment by atorin** [comment]
@janainawittner OK great, thanks for the review! I have implemented the changes in the main PR.
