### ISSUE TITLE
[Developer Quick Start] Access token validity

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#197]
Hi Alberto,

A couple of readers of our guide https://www.hubrise.com/developers/quick-start/ have recently showed confusion about access tokens.

They were not aware that access tokens were never expiring, so they were trying to figure out ways to automate the access token generation. Which of course they failed to achieve because of the required user permission. In their defense, access tokens have a limited lifespan in other APIs.

I think we should clarify that tokens do not expire, and that the process should only be done once per shop they need to connect.

**Comment by atorin** [comment]
I've added an important note to the doc. Let me know if that works.
