### ISSUE TITLE
[Flyt] OrderPad FAQ

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#454]
Below is a copy of questions/answers with Orient Ltd.

@estlv Can you create a short FAQ in apps/just-eat-flyt with these answers?

Don't worry too much about the format, just create a draft and I'll help you polish it.

---

Hi Estelle, good morning!

I have few questions regarding the above which are more concerning the Justeat orderpad:-

1. MUST I turn on the Justeat order pad in order to have the order integration to work?
-> Yes, you have to turn the pad ON and to accept the order to be able to see it appearing on your HubRise account.

2. When the Justeat orderpad is ON, will it print order ticket? I need to be print when Justeat orderpad is ON.
-> Yes, a ticket will be automatically printed as soon as you accept the order. This is the default behavior. But you can also configure your pad to set printing when "Time to start cooking the order" or  "Accepted & time to cook". And you can also reprint a ticket when you wish using the "Print receipt" option on the corresponding order.

3. When the Justest orderpad is ON, can I accept order and update order status from Justeat orderpad too?
-> When the order pad is ON and an order comes, you will hear a beep until you accept the order on the pad. When you press the "Accept" button, you change the status order to "Accepted". Then you can also change it to "Prepared" on the pad.

---

**Comment by estlv** [comment]
Jamie McCallum from Flyt said that the auto-accept mode is just a toggle they enable during onboarding. 
As for disabling, he doesn't think this can be done on the order pad. 
Ideally Flyt should thus be contacted to enable/disable this mode.

**Comment by janaina-wittner** [comment]
Final confirmation from Chris Stroud (Flyt), the orderpad needs to be on.
