### ISSUE TITLE
Implement a blog

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#46]
We need to add a blog on our website.

For now it will be in English only but copied to both the FR & EN sites (like the API documentation).

The HTML had already been done a while ago (in 2017): https://github.com/HubRise/hubrise-marketing-site

The 2 pages we need to add are: `build/article.html` and `build/blog.html`

No need for a comment section. Instead we will simply add an expendable box at the bottom "Comment this article", with the same style as the feedback component: 
![image](https://user-images.githubusercontent.com/5095197/72822273-19805300-3c72-11ea-85a7-a9a41a814d68.png)
When the block is expanded, it will propose to send us an email or share a comment on Twitter (not sure about the exact copy yet)

Also, what do you think about the search box? Is that doable in Gatsby?

**Comment by Ozerich** [comment]
> Is that doable in Gatsby?

Dont worry if smth is not doable in framework. We can create ourself features what you want!

**Comment by antmonnier** [comment]
> > Is that doable in Gatsby?
> 
> Dont worry if smth is not doable in framework. We can create ourself features what you want!

Hehe was expecting no less from you :)
Maybe create a first version of search then I'll have the designer review and suggest improvments?

**Comment by Ozerich** [comment]
@antmonnier can you check? I am waiting for your wishes to improve
