### ISSUE TITLE
[WooCommerce] Update documentation: discounts, payment methods, expected time, and service type

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#516]
We have just released an improved version of the bridge, which offers more configuration settings:

- Users can configure up to 5 payment methods. For each method, they specify the WooCommerce ID (the one that comes in the "payment_method" field of the WooCommerce payload), and the corresponding ref code that is encoded to HubRise. WooCommerce payment ids are standard and non configurable. You can get them in the WooCommerce back office by looking at the URL of each payment method page: 
![image](https://user-images.githubusercontent.com/5095197/150530259-11e4343f-38c9-4a95-bc9d-1af420964024.png)
- Discount ref code is now configurable.
- Expected time: depending on the plugin used, expected time can either be encoded in one or two metadata fields. In the former scenario, we support times encoded in ISO 8601 and Unix format. In the latter one, date and time should respectively be in `dd/mm/yyyy` and `hh:mm` formats. If it helps, check our [test case scenarios](https://github.com/HubRise/bridges/blob/cd15ed2a49d0e9a06f34cf93bfc30c56be67bf8d/bridges/woocommerce/spec/lib/woocommerce/to_hubrise/order_encoder_spec.rb#L46) or [the implementation](https://github.com/HubRise/bridges/blob/cd15ed2a49d0e9a06f34cf93bfc30c56be67bf8d/bridges/woocommerce/app/lib/woocommerce/to_hubrise/order_encoder.rb#L41).
- Service type: same as expected time, encoding depends on the plugin used. We assume it is passed in one metadata field, and we can configure both the metadata key, and the 3 possible values (for delivery, collection, and eat-in).

Can you please update the documentation with these changes?

**Comment by antmonnier** [comment]
Clarification about `Send orders with status "On hold" to HubRise` - this is used for orders with wire transfers.

Orders with wire transfers are initially set to "on-hold" in WooCommerce and they require manual status change to "processing" upon payment receipt. As opposed to credit card orders, which are created as "processing".

**Comment by albert9168** [comment]
@antmonnier Hi! One question: when an order with status `processing` or `on-hold` is sent to HubRise, which order status has it in HubRise? Do you set them both based on the configuration for "new" orders?

<img width="443" alt="Screenshot 2023-10-17 at 20 51 00" src="https://github.com/HubRise/website/assets/98554663/da6d6fe2-77eb-4761-ad8b-8063a035448e">

**Comment by antmonnier** [comment]
Hi @albert9168 

> Do you set them both based on the configuration for "new" orders?

Yes we do

**Comment by albert9168** [comment]
Thanks @antmonnier! Can you also clarify how the **Order item metadata** and **Multi-site** sections work?

**Comment by antmonnier** [comment]
Hi @albert9168 .

**Multi-site**: When multiple locations share the same website, we need to associate each order with a location. To achieve this, the website must include a metadata key with each order, and assign a different value to each store. The WooCommerce configuration lets you define the key, and the value corresponding to the current location. With these settings configured, any order received with a different value will be ignored by the bridge.

**Order item metadata**: WooCommerce orders often include a batch of metadata at the item level. Each key/value is converted as an option in HubRise by default, unless specified otherwise in this section. The available alternative choices are:
- Assume that the value is the SKU name (e.g. "Large" or "Medium").
- Assume that the value should be used to populate the item's customer notes.
- Or discard the value, meaning that it will not be converted to an option, a SKU name, or customer notes.
