### ISSUE TITLE
[LIGHTSPEED] FAQ update - orders not received in the EPOS

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#528]
Hi @albert9168, not sure if this has been documented yet but we often have this issue. 

An order is sent to HubRise. Lightspeed is connected, or appear connected but orders are rejected.

See for instance: https://manager.hubrise.com/orders/d8jr2m?account_id=w5qjj

{
  "status": "rejected",
  "seller_notes": "Order could not be sent to the restaurant. Please contact the restaurant to repeat your order.",
  "custom_fields": {
    "epos": {
      "rejection": {
        "info": {
          "reason": "The specified business location doesn't accept online orders at the moment.",
          "thirdPartyReference": "16y3z|w5qjj-0|d8jr2m",
          "businessLocationId": 25159918419969,
          "status": "FAILURE",
          "type": "ORDER"
        }

It simply means that orders have not been activated in the EPOS. 
We have this documentation for it : https://www.hubrise.com/apps/lightspeed-restaurant/faqs/troubleshooting-failed-orders/#api-activation-in-the-tablet

But Lightspeed support generally sends another screenshot with the following instructions (testing your FR):  
"Effectivement, ce message d'erreur signifie que les commandes en lignes ne sont pas autorisées sur la caisse. 
 Pour vous assurez, vous devez sur l'iPad, sur l'application Lightspeed, vérifier que l'icone du petit panier est en vert, sinon, il faudra cliquer dessus pour activer les commandes en ligne."

![Lightspeed rejected orders](https://user-images.githubusercontent.com/98127488/152869643-7f419eef-ab27-4d02-a2d0-fb60ce29d999.png)

Is it the same thing?
The icon does not show in the same place. Should we include:
-  the typical error message we get in the logs : "Order could not be sent to the restaurant. Please contact the restaurant to repeat your order.",
- and this new screenshot to our documentation?

**Comment by antmonnier** [comment]
I have actually already included this request in https://github.com/HubRise/website/pull/527#issuecomment-1029976586

Closing as duplicate.
