### ISSUE TITLE
[Lightspeed] what happens when the Lightspeed does not enable the integration for HubRise

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#536]
Hi @albert9168 and @antmonnier, 

I think we are in the process of documenting all Lightspeed errors.

Here is an example of what happens when Lightspeed is connected but we never requested them to enable the HubRise integration. 

The order is not received in the EPOS at all. 

In the HubRise back office we see Lightspeed Restaurant Bridge → HubRise
https://manager.hubrise.com/orders/5vm47j?location_id=wvve5-15
{
  "status": "received"
}

In the Lightspeed Restaurant Bridge we see Bridge → Lightspeed Restaurant response but no more actions thereafter
https://lightspeed-restaurant.hubrise-apps.com/operations/9032763?app_instance_id=zeey5
{
  "status": "ok"
}

We had simply to contact Lightspeed and get them to activate HubRise and the needed channels.

**Comment by albert9168** [comment]
@janaina-wittner Added a new page in #535.
