### ISSUE TITLE
[HUBRISE APP INSTALLATION] new tap

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#559]
@antmonnier, when you connect a Bridge, it opens in a new tab now, this is great! 
However, when you return to the back office, we are still in the **View available apps** page and the App **Connect** popup and buton are still open. This is a little strange. 

I think we should be on the HubRise **CONNECTIONS** Page
Or on the **View available apps** without any popup opened. 

See screenshot of the hubrise manager when we go back to it:
<img width="1582" alt="Screenshot 2022-03-17 at 12 21 05" src="https://user-images.githubusercontent.com/98127488/158799010-d11f54f1-d8c7-4716-9c8b-9bf3a62c1884.png">

**Comment by antmonnier** [comment]
Tracked in https://github.com/HubRise/manager/issues/284

**Comment by antmonnier** [comment]
Fixed
