### ISSUE TITLE
Extra spacing in bullet lists

### ISSUE THREAD

**Issue by albert9168** [HubRise/website#600]
**Issue 1**. Every nested level of bullet lists adds an extra line break to the following text.

<img width="939" alt="Screenshot 2022-05-01 at 16 09 18" src="https://user-images.githubusercontent.com/98554663/166149841-149be952-660b-4b44-b2c5-08ea6e6fbe61.png">

**Issue 2**. A bullet list nested inside a numbered list produces an unpleasant line break with the following numbered point.

<img width="935" alt="Screenshot 2022-05-01 at 16 09 50" src="https://user-images.githubusercontent.com/98554663/166149848-de79fee9-fc96-4fd1-96d5-da05eff6c992.png">

**Comment by antmonnier** [comment]
Fixed.

Now the following markdown:

```
## Issue 1

- Item

List

- Item
  - Item

One-line break

- Item
  - Item
    - Item

Two-line break

- Item
  - Item
    - Item
      - Item

Three-line break

## Issue 2

1. Step one

2. Step two
   - Substep

3. Step three
```

Renders as:

![image](https://github.com/HubRise/website/assets/5095197/b8b2c309-12c0-44ff-84dc-372f0a85210f)
