### ISSUE TITLE
Add support for animated GIFs

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#68]
It looks like animated GIFs are not supported - if I link such an image in the markdown:
![image](https://user-images.githubusercontent.com/5095197/74521552-d6846900-4f19-11ea-9f18-ec7c4af524a8.png)

I'm getting this display:
![image](https://user-images.githubusercontent.com/5095197/74521585-df753a80-4f19-11ea-8138-a9a645c8a902.png)

Can you enable this image type?
Or maybe the issue is that I'm using an image which is too big (1.3Mb) and in this case what would be the size limit?

**Comment by antmonnier** [comment]
Also @Ozerich what do you think about using mp4 instead of gifs?
Is it well supported by browsers?
And does Gatsby support mp4?

**Comment by Ozerich** [comment]
@antmonnier mp4 is better than gif. Because it is supported by all browsers, gif is not good in IE.

As for Gatsby, we don't need think about Gatsby in this case, it will be okay

**Comment by antmonnier** [comment]
OK then let's add support for both formats and we'll recommend contributors to prefer mp4
