### ISSUE TITLE
[App4] documentation

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#692]
Hi @albert9168, 

We have an online documentation for App4 which was never finalised. 
Here it is: https://www.hubrise.com/apps/app4

The integration was on stanby for ages, with no connection done. 
Recently, App4 updated the integration with HubRise. It does a lot more than it use to, including pull orders and customer info.

The updated integration sheet is here:
https://drive.google.com/drive/u/1/folders/1r8s4xAG1ZKNBZAI1iZBNqmpZx7DNZHb-

I asked App4 for a test account again. You were in CC of the email. 
We never got a test account. Two years ago, when we worked on the first documentation, they said they could not provide one. I am hoping they can now. Fell free to contact Ian directly asking how some things are done if he cannot provide any way for us to connect and test: Ian Chambers / CEO / ian@goapp4.com

It's important to include in this documentation the following sections :
- **Pull orders**: App4 can now pull orders from HubRise, including Food Delivery Platform orders. We need to understand the workflow within App4 to see orders, and change their statys.
- **Push orders**: I suppose, there will not be much here.... perhaps specificities to orders they sent.
- **Food Ordering Platform**: we need to know how to configure the Food Delivery Platform Bridge for App4
- **Inventory**: have they integrated it? If so, we can explain that products with inventory = 0 will be removed from food delivery platforms.
- **Pull catalog**: how does it work? A lot of information is missing in the existing documentation. 
- **Map ref codes**: I think we need to map ref codes for the integration of food delivery platforms to work. I think these ref codes can be created on App4. @fsantucci, connected a restaurant recently. He might have some information to share, so do not hesitate to liaise with him. Félix is amazing and does most of our support now a days in both EN & FR.
- **and anything else you see fit :-)**

For information, the former writer who worked on the App4 documentation has a lot of questions to ask. I think we never got a reply to any of them. Not entirely certain. It might be worth for you to look at the list of questions in the **Description** section of this Trello card: https://trello.com/c/1VS3jIEC/7-documentation. Select **Show full description** to see the **Question from John, the former tech writer**.

**Comment by janaina-wittner** [comment]
@albert9168, we have a test account for App4 now: https://github.com/HubRise/support/wiki/Test-Accounts#app4

**Comment by antmonnier** [comment]
@janaina-wittner I've just merged the PR.

Re inventory, I have no information that this was integrated, and I cannot see any inventory requested performed in their test account.
