### ISSUE TITLE
[APPS FILTER] opening on the page footer

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#728]
The **Apps** page filters work fine when you click from one filter to the next. 

However, when you:
1. click on a filter, 
2. then you scroll down to the page botom 
3. and you select a filter
Instead of opening it at the top of the items you filtered, it shows the footer and you need to scroll up the page to see the content of the page.

**Comment by antmonnier** [comment]
This page has been revamped, and scrolling now works correctly. Closing.
