### ISSUE TITLE
Replace gatsby-remark-copy-linked-files-with-poster with gatsby-remark-copy-linked-files

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#78]
Hi @Ozerich 

When `gatsby-remark-copy-linked-files` is released with your change (https://github.com/gatsbyjs/gatsby/pull/22032) we can remove `gatsby-remark-copy-linked-files-with-poster`

**Comment by Ozerich** [comment]
Done in PR [https://github.com/HubRise/website/pull/72](url)
