### ISSUE TITLE
Content file organization

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#81]
File organization under `content` is not very logical (my fault) and it forces breadcrumb generation to be hardcoded in `documentation.jsx`, which makes the content difficult to extend with new chapters.

Here are the proposed changes:
- In all `customization.yaml`, rename the `base_path` field into `path_override`, and remove the leading `/` in its value. So for instance `base_path: /developers` becomes `path_override: developers`. This will now represent the relative path of the chapter rather than its absolute path.
- Move the 3 subfolders in `general` up one level (so move them to the root level of `content`). Empty the 2 customization.yaml files since we don't need to override the path of the root folder.
- Add 2 subfolders `en` and `fr` under the `apps` folder. Both will contain a single `customization.yaml` file which will define 2 properties: `name: Apps` and `path_override: apps`. It's only a concidence that the FR and EN words are identical :)
- Move the `api` folder under the `developers` folder. From now the API pages will be hosted under the `/developers` path so for instance `/api/general-concepts` will now be hosted under `/developers/api/general-concepts`. I'll create nginx 302 redirections to keep the previous pages working.
- In `on_create_node.js` rely on the parent chapters' `path_override` rather than on `fileAbsolutePath` to generate the URL of each page. Use `path_override` recursively on each parent chapter (except the root level) so that each part of the path of a deep nested page can be localized.
- In `documentation.jsx` remove the `/developers` or `/api` hardcoding in the `getBreadcrumbs` function and run recursively through the `customization.yaml` files of the parent chapters to localize the breadcrumbs.

**Comment by antmonnier** [comment]
Suggested file organization:

```
content
    apps
        en
            customization.yaml
        fr
            customization.yaml
        ikentoo
            en
                customization.yaml
                overview.md
                ...
            images
                logo_ikentoo.png
                ...
    developers
        api
            en
                callbacks.md
                customization.yaml
                ...
        en
            authentication.md
            customization.yaml
            ...
    en
        customization.yaml
    fr
        customization.yaml
    images
        coming_soon.mp4
        ...
```

**Comment by Ozerich** [comment]
Done in this PR [https://github.com/HubRise/website/pull/86](url)

**Comment by antmonnier** [comment]
All done, thanks @Ozerich !
