### ISSUE TITLE
[CATALOG MANAGER] documentation update, new structure, new feature

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#828]
Hi Alberto,

We need an update to the Catalog Manager documentation: https://www.hubrise.com/apps/catalog-manager. 
Changes needed are related to the current structure, and to new features which were recently added to it.

---

**Things that bothers us in the current structure**
- The User Interface page refers to Deals, Discount and Charges. We have the same headers in the [Deals, Discounts and Charges](https://www.hubrise.com/apps/catalog-manager/deals-discounts-charges/) section. 
- The User Interface refers to [Catalogs](https://www.hubrise.com/apps/catalog-manager/catalogs/) and again, we have the same heading in the [Catalogs](https://www.hubrise.com/apps/catalog-manager/user-interface/#catalogs) section.

I think the User Interface section could be used to describe this part:
<img width="1432" alt="Screenshot 2023-08-02 at 15 14 55" src="https://github.com/HubRise/website/assets/98127488/3fe0e0f9-e986-4c22-a5f4-08c74f2684ca">

You might be able to re-use some of the content we have in : https://www.hubrise.com/apps/deliveroo/user-interface/

While flattening this one 
<img width="138" alt="Screenshot 2023-08-02 at 15 14 36" src="https://github.com/HubRise/website/assets/98127488/42ffe14e-2204-46b1-afe2-1d249de99fcb">

---

**New Feature**

Here is how we described it to clients in various emails we sent:

Vous pourrez ajouter des variantes (exemple: "Deliveroo", "Uber", ... ou "Prix élevés",..) comme ci-dessous:
![image (12)](https://github.com/HubRise/website/assets/98127488/076595f9-71e8-4d2c-8895-29176c40ee1c)

L'option Grille en haut de page vous permet de mieux visualiser les variantes:
![unnamed (2)](https://github.com/HubRise/website/assets/98127488/58ca6a7f-5889-4df5-b1cb-ca3851b77f1c)

Le catalogue est édité depuis le mode édition. 
Vous pouvez ensuite faire vos modifications dans la grille par variante si différence par rapport au menu d'origine.
Exemple: Prix supérieur sur Deliveroo et produit non actif sur Uber:
![unnamed (3)](https://github.com/HubRise/website/assets/98127488/2a967f83-c54c-4378-a7ba-961558cb621f)

**What you need to know about variants**
The **Default** column appears in the **Grid** mode when we add a variant. 
If you add a product with a price, it will replicate its price and availability into all variants. 
If you tick out a product using the **Enabled** column, in the **Default** section of the Grid, the product will be disabled for all variants.

**Comment by janaina-wittner** [comment]
@antmonnier, check if you want to add anything to these instructions before sending the project to @albert9168.

**Comment by antmonnier** [comment]
Here is the structure I propose:

- Overview (no change)
- Connect to HubRise (no change)
- Launch Catalog Manager. Just rename the existing page.
- User Interface.
  - Move the content of each section into the relevant page below.
  - Instead, this page should describe the common elements in the user interface (including the edit/grid/preview menu & the settings dialog)
- Catalogs:
  - Move the [Duplicate catalog](https://www.hubrise.com/apps/catalog-manager/faqs/duplicate-catalog/) FAQ into this page
  - Conversely, make the existing "Populate a Catalog from Another App" an FAQ page
  - In the "Create a Catalog" section, assume the user is already logged into Catalog Manager, no need to explain how to open it, as this duplicates the "Launch Catalog Manager" page
- Products: move the relevant content from the current "User Interface" and "Products and Options" pages into this new page.
- Options: same as above
- Deals: same as above
- Discounts: same as above
- Charges: same as above
- Grid mode
- Preview mode
- FAQs

**Comment by janaina-wittner** [comment]
@albert9168, I have done a web presentation of the catalog manager variants yesterday. There is an important point that came out of the discussion : the flexibility we have to connect a variant per Location> Bridge or App. It means that we can have apps in the one location that uses different variants. 

You should include an IMPORTANT NOTE, saying that all HubRise Bridges support this variant, but not all apps for now. The reader should refer to the app documentation to know if it is supported.

**Comment by albert9168** [comment]
@janaina-wittner @antmonnier Hi! Many thanks for the suggestions, I'll start working on this and will let you know if I have any questions.
