### ISSUE TITLE
Discounts label says "Title"

### ISSUE THREAD

**Issue by albert9168** [HubRise/website#873]
In the **Catalogs** page of the back office, the **Discounts** tab has **Title** as a label.

<img width="953" alt="Screenshot 2023-10-02 at 22 00 43" src="https://github.com/HubRise/website/assets/98554663/7176045b-a30e-4857-a690-581421532d70">

**Comment by antmonnier** [comment]
It's just been fixed. We're lucky you have an eagle eye!
