### ISSUE TITLE
Favicon on Safari

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#893]
The favicon on Safari does not look great for the website hubrise.com.
It looks fine on the right, for the HubRise back office manager.hubrise.com

<img width="359" alt="Screenshot 2023-11-01 at 16 05 05" src="https://github.com/HubRise/website/assets/98127488/90fcc48e-8f12-4508-87a9-9d42ec9d9f90">

**Comment by antmonnier** [comment]
This is for you @felixlopz

**Comment by antmonnier** [comment]
Fixed on master
