### ISSUE TITLE
[CATALOG MANAGER] Grid scroll bug

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#912]
Hi @antmonnier, there is a problem with the scrolling of the Catalog Manager grid table on HunRise. 

Tested on Safari and Chrome / Pizzaphone account / MASTER wy9qr catalog:
https://catalog-manager.hubrise-apps.com/catalogs/wy9qr/grid/skus?app_instance_id=137m3

<img width="1172" alt="Screenshot 2023-11-13 at 10 45 12" src="https://github.com/HubRise/website/assets/98127488/14cf0178-d534-450a-bc40-d0eb9abf7e0b">

The issue appears in both Safari and Chrome browsers.

**Comment by antmonnier** [comment]
Fixed and deployed.
