### ISSUE TITLE
[WEBSITE] bread crumbs not taking path_override into consideration

### ISSUE THREAD

**Issue by janaina-wittner** [HubRise/website#918]
Hi @antmonnier, bread crumbs are not taking `path_override` into consideration. Needs a global fix.

<img width="1335" alt="Screenshot 2023-11-23 at 10 35 05" src="https://github.com/HubRise/website/assets/98127488/7bd9a9e4-6fe2-4a55-b84d-a13d691125b9">

**Comment by antmonnier** [comment]
The problem is inconsistent values of `path_override` between `content/apps/lightspeed-restaurant/faqs/fr/customization.yaml` and `content/apps/lightspeed-restaurant/fr/faqs.md`. One uses `faq`, the other uses `faqs`.

I'll make a global fix to use the singular form across all our FR documentation.

**Comment by antmonnier** [comment]
Ok, [changes have been made](https://github.com/HubRise/website/pull/919/files): `path_override` and page name/title now use the singular form in French.

Remember that you still need to use the plural form in the links, as links are always in EN in Markdown, and dynamically translated to FR wrt `path_override`.
