### ISSUE TITLE
Links with anchors 404

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#94]
On this page https://www.hubrise.com/developers/api/catalog-management/#restrictions if you click on the first Date link:
![image](https://user-images.githubusercontent.com/5095197/81316663-25125100-908c-11ea-864b-9cb35fd27a52.png)

You get a 404:
![image](https://user-images.githubusercontent.com/5095197/81316677-2c395f00-908c-11ea-944d-b8ebb0281606.png)

If you refresh the 404 page the content is now displayed:
![image](https://user-images.githubusercontent.com/5095197/81316726-3b201180-908c-11ea-9ade-fcd9d184365e.png)

**Comment by Ozerich** [comment]
Fixed in #97
