### ISSUE TITLE
[Shopify] Update configuration page

### ISSUE THREAD

**Issue by antmonnier** [HubRise/website#947]
Many features have been added to the Shopify Bridge configuration page since the last documentation update.

We need to update the [Shopify Bridge configuration page](https://www.hubrise.com/apps/shopify/configuration) to include the new features. All images are already in the `images` folder.

An example of recently updated configuration pages is [Deliveroo Bridge configuration page](https://www.hubrise.com/apps/deliveroo/configuration). Note that Deliveroo shows the whole order section in one image, but we decided to split into subsections for Shopify, as the section was too long.

**Comment by antmonnier** [comment]
cc @janaina-wittner

**Comment by albert9168** [comment]
Thanks @antmonnier! Just a quick question: in the Payments section, is there a trick to figure out the payment name used on Shopify?

**Comment by antmonnier** [comment]
Not sure, but [this post](https://community.shopify.com/c/sales-channels-payments-apps-and/retrieve-enabled-payment-methods-by-api/td-p/2226063) suggests that the current best option is to place test orders.

**Comment by albert9168** [comment]
Thanks, that makes sense. I used this approach in the docs.
